### ISSUE TITLE
Network Component: Random AccessViolationException without Dialog

### ISSUE THREAD

**Issue by WiiPlayer2** [glzr-io/glazewm#437]
I still don't know why but sometimes one of my devices GlazeWM just crashes without log entry or dialog. I did launch GlazeWM directly from the terminal to get a stack trace but at the moment I do not know how to reproduce and what the actual issue is.

Terminal output:
```
...
10/25/2023 14:03:20[WindowFocusedHandler] Native focus event: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
10/25/2023 14:03:20[Bus] Command SetFocusedDescendantCommand invoked.
10/25/2023 14:03:20[Bus] Command SetActiveWindowBorderCommand invoked.
10/25/2023 14:03:47[WindowFocusedHandler] Native focus event: ms-teams TeamsWebView
10/25/2023 14:03:47[Bus] Command SetFocusedDescendantCommand invoked.
10/25/2023 14:03:47[Bus] Command SetActiveWindowBorderCommand invoked.
10/25/2023 14:03:54[WindowFocusedHandler] Native focus event: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
10/25/2023 14:03:54[Bus] Command SetFocusedDescendantCommand invoked.
10/25/2023 14:03:54[Bus] Command SetActiveWindowBorderCommand invoked.
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr, System.Type)
   at Vanara.Extensions.InteropExtensions.GetValueType(IntPtr, System.Type, System.Type, Int32, Vanara.PInvoke.SizeT)
   at Vanara.InteropServices.IntPtrConverter.Convert(IntPtr, UInt32, System.Type, System.Runtime.InteropServices.CharSet)
   at Vanara.Extensions.InteropExtensions.ToStructure[[Vanara.PInvoke.IpHlpApi+IP_ADAPTER_ADDRESSES, Vanara.PInvoke.IpHlpApi, Version=3.4.12.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]](IntPtr, Vanara.PInvoke.SizeT, Int32)
   at Vanara.Extensions.InteropExtensions+<LinkedListToIEnum>d__14`1[[Vanara.PInvoke.IpHlpApi+IP_ADAPTER_ADDRESSES, Vanara.PInvoke.IpHlpApi, Version=3.4.12.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]].MoveNext()
   at System.Linq.Enumerable.TryGetFirst[[Vanara.PInvoke.IpHlpApi+IP_ADAPTER_ADDRESSES, Vanara.PInvoke.IpHlpApi, Version=3.4.12.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]](System.Collections.Generic.IEnumerable`1<IP_ADAPTER_ADDRESSES>, System.Func`2<IP_ADAPTER_ADDRESSES,Boolean>, Boolean ByRef)
   at GlazeWM.Infrastructure.WindowsApi.NetworkService.GetPrimaryAdapter()
   at GlazeWM.Bar.Components.NetworkComponentViewModel.getNetworkIcon()
   at GlazeWM.Bar.Components.NetworkComponentViewModel.CreateLabel()
   at GlazeWM.Bar.Components.NetworkComponentViewModel.<.ctor>b__8_0(Int64)
   at System.Reactive.AnonymousSafeObserver`1[[System.Int64, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(Int64)
   at System.Reactive.HalfSerializer.ForwardOnNext[[System.Int64, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reactive.ISink`1<Int64>, Int64, Int32 ByRef, System.Exception ByRef)
   at System.Reactive.Concurrency.Scheduler+<>c__67`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<SchedulePeriodic>b__67_0(System.ValueTuple`2<System.__Canon,System.Action`1<System.__Canon>>)
   at System.Reactive.Concurrency.DefaultScheduler+PeriodicallyScheduledWorkItem`1+<>c[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Tick>b__5_0(PeriodicallyScheduledWorkItem`1<System.ValueTuple`2<System.__Canon,System.__Canon>>)
   at System.Reactive.Concurrency.AsyncLock.Wait(System.Object, System.Delegate, System.Action`2<System.Delegate,System.Object>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
Unhandled exception. waldemar.tomme@waldemar-laptop    ~                                                                                                                  pwsh   98  5h 57m 50.223s 
  > System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived, CloseSent'              [ 14:07:00 ]
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at GlazeWM.Domain.Common.IpcClient.DisconnectAsync() in C:\Users\larsb\repos\GlazeWM\GlazeWM.Domain\Common\IpcClient.cs:line 82
   at GlazeWM.App.Watcher.WatcherStartup.Run(Int32 ipcServerPort) in C:\Users\larsb\repos\GlazeWM\GlazeWM.App.Watcher\WatcherStartup.cs:line 54
   at GlazeWM.App.Program.StartWatcher(Boolean isSingleInstance) in C:\Users\larsb\repos\GlazeWM\GlazeWM.App\Program.cs:line 124
   at GlazeWM.App.Program.Main(String[] args) in C:\Users\larsb\repos\GlazeWM\GlazeWM.App\Program.cs:line 62
   at GlazeWM.App.Program.<Main>(String[] args)
```

P.S.: I just saw that the exception happens in the Network Component. I think it might be a good idea to generally catch exceptions from components but I did not look into the code yet to see if it's currently possible.

P.P.S.: I just realized you cannot catch AccessViolationException ¯\\\_(ツ)\_/¯

**Comment by Video-Nomad** [comment]
Similar issue with the Weather component. When there is no internet connection (happened to me today) the weather component throws an exception on GlazeWM startup, blocking the app completely.
Output:
```
10/28/2023 20:17:36[IpcServerStartup] Starting IPC server on port 6123.
10/28/2023 20:17:36[Bus] Command PopulateInitialStateCommand invoked.
10/28/2023 20:17:36[Bus] Command EvaluateUserConfigCommand invoked.
10/28/2023 20:17:36[Bus] Command RegisterKeybindingsCommand invoked.
10/28/2023 20:17:36[Bus] Command AddMonitorCommand invoked.
10/28/2023 20:17:36[Bus] Command AttachContainerCommand invoked.
10/28/2023 20:17:36[Bus] Command ActivateWorkspaceCommand invoked.
10/28/2023 20:17:36[Bus] Command AttachContainerCommand invoked.
10/28/2023 20:17:36[IpcMessageHandler] IPC message received: windows.
10/28/2023 20:17:36[IpcMessageHandler] IPC message received: subscribe -e window_managed,window_unmanaged.
Unhandled exception. System.Net.Http.HttpRequestException: No such host is known. (api.open-meteo.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GlazeWM.Infrastructure.Services.WeatherService.GetWeatherAsync(Single latitude, Single longitude) in D:\Dev\Windows\GlazeWM_dev\GlazeWM.Infrastructure\Services\WeatherService.cs:line 29
   at GlazeWM.Bar.Components.WeatherComponentViewModel.UpdateLabel() in D:\Dev\Windows\GlazeWM_dev\GlazeWM.Bar\Components\WeatherComponentViewModel.cs:line 38
   at GlazeWM.Bar.Components.WeatherComponentViewModel.<.ctor>b__5_0(Int64 _) in D:\Dev\Windows\GlazeWM_dev\GlazeWM.Bar\Components\WeatherComponentViewModel.cs:line 33
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived, CloseSent'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at GlazeWM.Domain.Common.IpcClient.DisconnectAsync() in D:\Dev\Windows\GlazeWM_dev\GlazeWM.Domain\Common\IpcClient.cs:line 82
   at GlazeWM.App.Watcher.WatcherStartup.Run(Int32 ipcServerPort) in D:\Dev\Windows\GlazeWM_dev\GlazeWM.App.Watcher\WatcherStartup.cs:line 51
   at GlazeWM.App.Program.StartWatcher(Boolean isSingleInstance) in D:\Dev\Windows\GlazeWM_dev\GlazeWM.App\Program.cs:line 124
   at GlazeWM.App.Program.Main(String[] args) in D:\Dev\Windows\GlazeWM_dev\GlazeWM.App\Program.cs:line 62
   at GlazeWM.App.Program.<Main>(String[] args)
   ```

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
