### ISSUE TITLE
Program does not start

### ISSUE THREAD

**Issue by JPhusion** [glzr-io/glazewm#80]
After about using the newest release for 2 weeks, it no longer was able to start. When double clicking on the .exe, nothing happened. Reinstall did not solve the issue. I reverted back to the previous release for the last 2 weeks and that was working fine until today, when that stopped starting as well.

**Comment by lars-berger** [comment]
Huh, that's very strange. Could you send `C:\Users\<YOUR_USER>\.glaze-wm\errors.log`? It could be an error related to the user config, but that'd normally show an error dialog. Just in case, could you send a snippet of your user config as well?

**Comment by JPhusion** [comment]
[errors.log](https://github.com/lars-berger/GlazeWM/files/8852303/errors.log)
[config.txt](https://github.com/lars-berger/GlazeWM/files/8852309/config.txt)

Errors are foreign to me but it seems like the errors are from before yesterday with the latest error from 4/06, so not sure what's going on there. I had to upload the config as a txt as .yaml cannot be uploaded. Thanks for you help and this project... I can no longer imagine a workflow without it.

**Comment by jneiva0** [comment]
I'm having the same problem as @JPhusion 
The `errors.log` lastest error was from a few days ago
But here is some info that may be helpful.
This is a entry generated in the Windows Event Viewer when I try to start the .exe

```
Description: A .NET Core application failed. 
Application: GlazeWM_x64.exe Path: C:\Users\<MY_USER>\GlazeWM_x64.exe 
Message: Error: 
  An assembly specified in the application dependencies manifest (GlazeWM.deps.json) was not found: 
  package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.1.0' 
  path: 'Microsoft.VisualBasic.Core.dll' 

```

**Comment by graham** [comment]
I've been running into the same issue:

https://gist.github.com/graham/57d9df90289a124170fd6fce0514cf79

Attempting to open the GlazeWM application doesn't seem to add anything new to the error log either.

p.s. This is absolutely my favorite window manager, thank you for all the hard work, happy to provide additional details if it's helpful.

**Comment by graham** [comment]
Update.

When using the x86 version of the application i get an error similar to what @jneiva0 posted above. Using the x64 version I get the following error:

```
Description: A .NET Core application failed.
Application: GlazeWM_x64.exe
Path: C:\Users\USERNAME\Desktop\GlazeWM_x64.exe
Message: The application to execute does not exist: 'C:\Users\USERNAME\AppData\Local\Temp\.net\GlazeWM_x64\2lfEOU64CtpJH1Oi4TvGvh38O+4S1Co=\GlazeWM.dll'.
```

Do I need to install one of the .net static libs?

**Comment by graham** [comment]
Removing `C:\Users\USERNAME\AppData\Local\Temp\.net\GlazeWM_x64\` has resolved the issue for me! (I'll report back if the error returns)

**Comment by JPhusion** [comment]
@graham 's solution seems to work for me too. I'll report back if the error returns. Thank you.

**Comment by crimist** [comment]
Similar `errors.log` and \@graham's solution fixed it as well.

<details>
<summary>errors.log</summary>
<br>

```
6/11/2022 11:09:24 PM
A task was canceled.   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at GlazeWM.Bar.MainWindow.<>c__DisplayClass10_0.<OnSourceInitialized>b__1(Event event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Bar\MainWindow.xaml.cs:line 50
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 54
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at GlazeWM.Infrastructure.Bussing.Bus.RaiseEvent[T](T event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 71

6/11/2022 11:09:25 PM
A task was canceled.   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at GlazeWM.Bar.BarService.ExitApp() in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Bar\BarService.cs:line 81
   at GlazeWM.Bootstrapper.Startup.OnApplicationExit() in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Bootstrapper\Startup.cs:line 147
   at GlazeWM.Bootstrapper.Startup.<Run>b__10_1(Event event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Bootstrapper\Startup.cs:line 83
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 54
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at GlazeWM.Infrastructure.Bussing.Bus.RaiseEvent[T](T event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 71

6/11/2022 11:09:25 PM
A task was canceled.   at GlazeWM.Infrastructure.Bussing.Bus.RaiseEvent[T](T event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 76
   at GlazeWM.Infrastructure.Bussing.Bus.HandleError(Exception error) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 88
   at GlazeWM.Infrastructure.Bussing.Bus.RaiseEvent[T](T event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 76
   at GlazeWM.Domain.Monitors.CommandHandlers.RefreshMonitorStateHandler.Handle(RefreshMonitorStateCommand command) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Domain\Monitors\CommandHandlers\RefreshMonitorStateHandler.cs:line 58
   at GlazeWM.Infrastructure.Bussing.Bus.Invoke[T](T command) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 43

6/11/2022 11:09:25 PM
A task was canceled.   at GlazeWM.Infrastructure.Bussing.Bus.Invoke[T](T command) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 43
   at GlazeWM.Domain.Monitors.EventHandlers.DisplaySettingsChangedHandler.Handle(DisplaySettingsChangedEvent event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Domain\Monitors\EventHandlers\DisplaySettingsChangedHandler.cs:line 19
   at GlazeWM.Infrastructure.Bussing.Bus.RaiseEvent[T](T event) in C:\Users\larsb\repos\glazewm-1.4.2\GlazeWM.Infrastructure\Bussing\Bus.cs:line 57
```
</details>

**Comment by lars-berger** [comment]
The underlying framework used for the project used to be quite outdated and has now been upgraded to .NET 6 in the [latest release](https://github.com/lars-berger/GlazeWM/releases). Honestly not sure whether this will actually solve the issue that you guys are experiencing, but it's worth a shot. If the upgrade doesn't have any effect on the issue, the WM could do a wipe of the dir @graham mentioned when it's starting up.

@graham could you create a separate issue for the `"At least 1 workspace is required per monitor"` crash? How many workspaces do you typically have open when this happens? How many workspaces are defined in your user config?

**Comment by graham** [comment]
Will do, thank you!
